# Generated by Django 4.1 on 2022-11-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_superhero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
