# Generated by Django 4.2.4 on 2023-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='superhero',
            name='strengths',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weaknesses',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
