databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: plankton-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  - key: DJANGO_SUPERUSER_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: siah5054@bears.unco.edu
  - key: DJANGO_SUPERUSER_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: esiah
  - key: DJANGO_SUPERUSER_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: esiah
  github:
    branch: main
    repo: elmoresiahaan/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: superhero
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    python manage.py loaddata database.json
    python manage.py build database
    python manage.py createsuperuser --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Superhero
static_sites:
- environment_slug: html
  github:
    branch: main
    repo: elmoresiahaan/PythonWebApps
  name: superhero-static
  routes:
  - path: /static
  source_dir: Superhero/static
